### ISSUE TITLE
saasquatch: accountId and referralImage are wrong

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-saasquatch#1]
_From @ianstormtaylor on August 8, 2014 17:13_
- `accountId` should map to our `groupId` I think.
- `referralImage` should be a setting in the interface I think.

Here are the docs for the Saasquatch `init` method: http://docs.referralsaasquatch.com/squatchjs#init

_Copied from original issue: segmentio/analytics.js-integrations#383_

**Comment by ndhoule** [comment]
_From @maxdec on October 1, 2014 12:39_

:+1:

**Comment by hankim813** [comment]
This has been fixed
