### ISSUE TITLE
Add support for other SaaSquatch 'init' parameters

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-saasquatch#2]
_From @loganvolkers on May 9, 2014 17:38_

There are a few parameters missing for the SaaSquatch integration that are required to get things rolling.

The SaaSquatch integration already supports the custom traits of `accountId`, `referralImage` and `checksum`. We also need support for `mode` and `payment_provider_id`
- TODO: Add support for the trait `payment_provider_id` in `identify`
- TODO: Add support for the field `mode` in `init`

Ideally it would be handy if these parameters could be extensible. 
- TODO: Add generic extensible support for something like `saasquatch.otherCustomTrait1`

I would be happy to contribute the patch, I just need some guidance on the best practices for custom traits.

_Copied from original issue: segmentio/analytics.js-integrations#141_

**Comment by ndhoule** [comment]
_From @maxdec on October 1, 2014 12:38_

:+1:

**Comment by hankim813** [comment]
This has been implemented :)
